services:
  app:
    build:
      context: .
      target: development
    ports:
      - 3000:3000
    environment:
      - PORT=3000
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
    networks:
      - config-store-network

networks:
  config-store-network: